### ISSUE TITLE
Idea: Don't accept new users' submissions

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#110]
- New users submissions are hidden by default with a new column (not shadowHidden)
- Every submission, check if there are submissions by other approved users that are 95% similar to their previous submissions (start out with 1, make this variable)
    - Unhide all user submissions making them "approved"

#423 should be improved to check if they are an approved submitter instead of just a submitter.

Moved from https://github.com/ajayyy/SponsorBlock/issues/422

**Comment by Joe-Dowd** [comment]
I think hidden new user submissions should count towards user acceptance (potentially with reduced weighting) with backtracking to also approve them. 
It's unlikely people will submit segments if there's an existing segment there (unless it's the wrong category, which is counter productive), so otherwise you're only accepting fast submitters into the pool.
Also, otherwise it could have the effect of further slowing the growth of visible submissions into uncommon video categories.

**Comment by ajayyy** [comment]
It would appear to further users as if no submission was ever there.
