### ISSUE TITLE
Investigate why server freezes when a connection to the db ever fails

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#372]
```
(node:3870) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 10.0.0.4:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
(node:3870) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3870) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

`Postgres.ts` should probably have a try/catch.

Since it doesn't crash, it doesn't cause it to restart and it instead gets stuck in a broken state.

**Comment by ajayyy** [comment]
https://github.com/brianc/node-postgres/issues/1789

**Comment by HanabishiRecca** [comment]
In any case, I think the server should handle unexpected events. At least just restart. Like:
```ts
const panic = (e: Error) => {
    console.error(e);
    // Hope for the best
    process.exit(1);
};

process.on('uncaughtException', panic);
process.on('unhandledRejection', panic);
```
Of course there should be a service/script that watches the process and restarts it.

**Comment by ajayyy** [comment]
Fix didn't work, same issue today

**Comment by qgustavor** [comment]
I don't know if I'm talking something you already know, if so, sorry, but by now error handling with promises don't makes Node crash by default unless you use something like the code above from HanabishiRecca. That have a reason: IIRC it allows you storing a rejected promise into a variable and handling the error later, then, as Node can't guess if you will deal with the error later or not, it don't crashes.

I tried checking the code and everything uses `await` ([`init()`](https://github.com/ajayyy/SponsorBlockServer/blob/ad3f2088efb289b007acfcc0badcb83a5a35d749/src/index.ts#L21) calls [`initDb()`](https://github.com/ajayyy/SponsorBlockServer/blob/ad3f2088efb289b007acfcc0badcb83a5a35d749/src/index.ts#L9) which calls [`db.init()`](https://github.com/ajayyy/SponsorBlockServer/blob/ad3f2088efb289b007acfcc0badcb83a5a35d749/src/databases/databases.ts#L64) which calls [`this.createDB()`](https://github.com/ajayyy/SponsorBlockServer/blob/ad3f2088efb289b007acfcc0badcb83a5a35d749/src/databases/Postgres.ts#L27) which calls [`client.connect()`](https://github.com/ajayyy/SponsorBlockServer/blob/ad3f2088efb289b007acfcc0badcb83a5a35d749/src/databases/Postgres.ts#L89) which seems to be the function that should be rejecting). Because of that rejections from a promise would go up to each calling function until some handles it. As seems that no function in this chain is handling errors and the [`init()`](https://github.com/ajayyy/SponsorBlockServer/blob/ad3f2088efb289b007acfcc0badcb83a5a35d749/src/index.ts#L21) function is being called without an error handler seems that it causes the `UnhandledPromiseRejectionWarning`. In the other hand, as it don't shows up in the error stack trace, I might be wrong... Anyway, I think HanabishiRecca suggestion is good.

**Comment by HanabishiRecca** [comment]
Also 9d2c5ed74e199eab217e8b7e655af5ca5a8181e5 better should be reverted, because
```ts
const client = await this.pool.connect();
const queryResult = await client.query({ text: query, values: params });
// If query failed, the client will never be released back to the pool
client.release();
```

**Comment by ajayyy** [comment]
`this.createDB()`

is only called once, so that shouldn't matter

***

> // If query failed, the client will never be released back to the pool

good catch, maybe that would probably work best in `finally`

**Comment by HanabishiRecca** [comment]
Pretty tough to say what is happening without a more detailed stack trace. Are you sure that the rejection happens exactly here?

**Comment by ajayyy** [comment]
Now logging a trace for next time 3335d541539bc1c88950f435800b9108311ed9f7

**Comment by ajayyy** [comment]
Will close this for now as I think it is solved this time...
