### ISSUE TITLE
Better metrics on where latency is occuring

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#492]
In the random spikes in the graph, what part is stalling?

Nginx? K8s proxy? sb-server? Redis? Postgres?

Postgres currently has a retry system, and redis has a timeout, so it seems more likely to be caused by nginx, k8s or sb-server itself.

![image](https://user-images.githubusercontent.com/12688112/184269736-7b9f8652-dbe2-46d1-b794-eff402d2e323.png)

**Comment by Zamion101** [comment]
From my experiences and projects, I recommend usage of Prometheus as metric server to collect metrics from services. Why Prometheus you may ask? Because is Pull-based Metric collection server rather than Push-based ones like Graphite or InfluxDB. You can easily scale any metric you want to collect. Also with the combination of Grafana you can easily create an Alarm to detect high latency spikes or downtime. I can open a Pull Request with the implementation of Prometheus metrics if you want me to do.
